In [1]:
import numpy as np

In [2]:
A = np.array([0, 1, 2])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [12]:
print(f"{A.shape=}")
print(f"{A[:,np.newaxis].shape=}")
print(f"{A[np.newaxis, :].shape=}")

A.shape=(3,)
A[:,np.newaxis].shape=(3, 1)
A[np.newaxis, :].shape=(1, 3)


In [6]:
A[:,np.newaxis] * B

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [7]:
(A[:,np.newaxis] * B).sum(axis=1)

array([ 0, 22, 76])

In [17]:
np.einsum('i,ij->ij', A,B)

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [18]:
A = np.array([[1, 1, 1],
             [2, 2, 2],
             [5, 5, 5]])

B = np.array([[0, 1, 0],
             [1, 1, 0],
             [1, 1, 1]])

In [19]:
A*B

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [20]:
(A*B).sum(axis=1)

array([ 1,  4, 15])

In [21]:
(A*B).sum(axis=0)

array([7, 8, 5])

In [27]:
np.einsum('ij,jk->jik', A, B)

array([[[0, 1, 0],
        [0, 2, 0],
        [0, 5, 0]],

       [[1, 1, 0],
        [2, 2, 0],
        [5, 5, 0]],

       [[1, 1, 1],
        [2, 2, 2],
        [5, 5, 5]]])